language: java
jdk: openjdk-ea

cache:
  directories:
    - $HOME/.m2

before_install:
  - java -version

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn package
